# Generated by Django 5.2.4 on 2025-08-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="chat_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
