# Generated by Django 5.2.4 on 2025-08-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="chat_id",
        ),
    ]
