# Generated by Django 5.2.4 on 2025-08-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
